### ISSUE TITLE
bottom of the tree sometimes gets cut

### ISSUE THREAD

**Issue by lunebellec** [SIMEXP/multiscale_dashboard#3]

**Comment by lunebellec** [comment]
that example is for the fronto parietal network. 
![screenshot from 2017-11-21 21-28-31](https://user-images.githubusercontent.com/1670887/33106959-dc6ef48c-cf02-11e7-8bf8-1c292c0c858a.png)

**Comment by jarmoza** [comment]
Fixed in commit 815676838ed7bbd7ed9d4fe0a63e24c6aa060547
